
	.equiv	CH_NULL,		0x00
	.equiv	CH_BACKSPACE,	0x08
	.equiv	CH_LF,			0x0a
	.equiv	CH_CR,			0x0d
	.equiv	CH_CAN,			0x18
	.equiv	CH_SPACE,		0x20		//" "
	.equiv	CH_EXCLAMATION,	0x21		//!
	.equiv	CH_DQUOTE,		0x22		//"
	.equiv	CH_POUND,		0x23		//#
	.equiv	CH_DOLLAR,		0x24		//$
	.equiv	CH_PERCENT,		0x25		//%
	.equiv	CH_AMPERSAND,	0x26		//&
	.equiv	CH_SQUOTE,		0x27		//'
	.equiv	CH_OPEN_PAREN,	0x28		//(
	.equiv	CH_CLOSE_PAREN,	0x29		//)
	.equiv	CH_ASTERISK,	0x2a		//*
	.equiv	CH_PLUS,		0x2b		//+
	.equiv	CH_COMMA,		0x2c		//,
	.equiv	CH_HYPHEN,		0x2d		//-
	.equiv	CH_MINUS,		0x2d		//-
	.equiv	CH_PERIOD,		0x2e		//.
	.equiv	CH_FSLASH,		0x2f		// /
	.equiv	CH_0,	0x30
	.equiv	CH_1,	0x31
	.equiv	CH_2,	0x32
	.equiv	CH_3,	0x33
	.equiv	CH_4,	0x34
	.equiv	CH_5,	0x35
	.equiv	CH_6,	0x36
	.equiv	CH_7,	0x37
	.equiv	CH_8,	0x38
	.equiv	CH_9,	0x39
	.equiv	CH_COLON,		0x3a		//:
	.equiv	CH_SEMICOLON,	0x3b		//;
	.equiv	CH_LESS_THAN,	0x3c		//<
	.equiv	CH_EQUAL,		0x3d		//=
	.equiv	CH_GREATER_THAN, 0x3e		//>
	.equiv	CH_QUESTION_MARK,0x3f		//?
	.equiv	CH_AT_SIGN,		0x40		//@

	.equiv	CH_A,	0x41
	.equiv	CH_B,	0x42
	.equiv	CH_C,	0x43
	.equiv	CH_D,	0x44
	.equiv	CH_E,	0x45
	.equiv	CH_F,	0x46
	.equiv	CH_G,	0x47
	.equiv	CH_H,	0x48
	.equiv	CH_I,	0x49
	.equiv	CH_J,	0x4a
	.equiv	CH_K,	0x4b
	.equiv	CH_L,	0x4c
	.equiv	CH_M,	0x4d
	.equiv	CH_N,	0x4e
	.equiv	CH_O,	0x4f
	.equiv	CH_P,	0x50
	.equiv	CH_Q,	0x51
	.equiv	CH_R,	0x52
	.equiv	CH_S,	0x53
	.equiv	CH_T,	0x54
	.equiv	CH_U,	0x55
	.equiv	CH_V,	0x56
	.equiv	CH_W,	0x57
	.equiv	CH_X,	0x58
	.equiv	CH_Y,	0x59
	.equiv	CH_Z,	0x5a
	.equiv	CH_OPEN_SQUARE,	0x5b	//[
	.equiv	CH_BSLASH,		0x5c	//\..
	.equiv	CH_CLOSE_SQUARE,0x5d	//]
	.equiv	CH_CARET,		0x5e	//^
	.equiv	CH__,			0x5f	//_
	.equiv	CH_OPEN_SQUOTE,	0x60	//`

	.equiv	CH_a,	0x61
	.equiv	CH_b,	0x62
	.equiv	CH_c,	0x63
	.equiv	CH_d,	0x64
	.equiv	CH_e,	0x65
	.equiv	CH_f,	0x66
	.equiv	CH_g,	0x67
	.equiv	CH_h,	0x68
	.equiv	CH_i,	0x69
	.equiv	CH_j,	0x6a
	.equiv	CH_k,	0x6b
	.equiv	CH_l,	0x6c
	.equiv	CH_m,	0x6d
	.equiv	CH_n,	0x6e
	.equiv	CH_o,	0x6f
	.equiv	CH_p,	0x70
	.equiv	CH_q,	0x71
	.equiv	CH_r,	0x72
	.equiv	CH_s,	0x73
	.equiv	CH_t,	0x74
	.equiv	CH_u,	0x75
	.equiv	CH_v,	0x76
	.equiv	CH_w,	0x77
	.equiv	CH_x,	0x78
	.equiv	CH_y,	0x79
	.equiv	CH_z,	0x7a
	.equiv	CH_OPEN_CURLY,		0x7b	//{
	.equiv	CH_VERTICAL_BAR,	0x7c	//|
	.equiv	CH_CLOSE_CURLY,		0x7d	//}
	.equiv	CH_TILDE,			0x7e	//~
	.equiv	CH_DELETE,			0x7f
